### ISSUE TITLE
How to change the color of the count number text which means second.

### ISSUE THREAD

**Issue by wann2** [rehmanmuradali/ticker#1]
Hi,

Thanks for the codes.
I'd like to change the default color of the count number text which is second.
At present, the color of the seconds is set to black.

**Comment by Srinagar67** [comment]
Hi,
yourCircularItem.setTextColor(getResources().getColor(R.color.yourcolor));

**Comment by rehmanmuradali** [comment]
Hello @wann2, this custom view is an extension of TextView. You can set color just like Android's text view. @Srinagar67 has mentioned one method or you can add android:textColor="@color/your_color" in the layout file.

**Comment by wann2** [comment]
Many Thanks for help
